highlight: true
sass_dir: scss
highlighter: rouge
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
  - jekyll-toc
exclude:
  - vendor
  - '**/node_modules'

# Site specific vars
name: Will Price
twitter: will_price_94
github: willprice
linkedin: will-price-aba5797b
